# Generated by Django 4.1.3 on 2022-12-26 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='photos/')),
                ('author', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
