# Generated by Django 4.1.3 on 2022-12-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
    ]
